## 数组操作
###  1. 查看数据形状


In [1]:
import numpy as np

a1 = np.array([1,2,3,4,5])
print(a1)

a1.shape

[1 2 3 4 5]


(5,)

In [2]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

a2.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [3]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

a3.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

###  2. 修改数组形状
**语句**：`reshape(shape, order='C' )`
**作用**：不改变数据的条件下修改形状

**参数说明**：

* shape：形状
* order：C-按行，‘F’-- 按列，‘A’–原顺序，‘k’ -元素在内存中的出现顺序



In [4]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

print(a.reshape(4,2))

# 再次查看数组形状发现只是临时修改      
print(a.shape)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(2, 4)


**语句**：`flatten( order='C')`

**作用**：展平的数组元素并拷贝一份，顺序通常是"C风格"

**注意**：修改返回的数组不会对原数组产生影响

**参数说明**：

* order：‘C’-按行，‘F’–按列，‘A’–原顺序，‘k’ -元素在内存中的出现顺序


In [5]:
c = np.array([[1, 2],[3, 4],[5, 6],[7, 8]])
print(c)

print(c.shape)

print(c.flatten())

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
[1 2 3 4 5 6 7 8]


### 3、数组和数的计算
numpy的广播机制造成的,在运算过程中,加减乘除的值被广播到所有的元素上面.


In [6]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
a + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [8]:
a - 1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
a * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [10]:
a / 10

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

### 4、数组和数组的计算
两数组相同维度下加减乘除


In [11]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

b = np.arange(11,21).reshape(2,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
a + b

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [13]:
a-b

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [14]:
a*b

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [15]:
a / b

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]])

#### 2行5列 VS 1行5列


In [16]:
a = np.arange(1,6).reshape(5,)
print(a)
b = np.arange(11,21).reshape(2,5)
print(b)

print(f"a+b的值是{a+b}")

print(f"a*b的值是{a*b}")

[1 2 3 4 5]
[[11 12 13 14 15]
 [16 17 18 19 20]]
a+b的值是[[12 14 16 18 20]
 [17 19 21 23 25]]
a*b的值是[[ 11  24  39  56  75]
 [ 16  34  54  76 100]]


#### 2行1列 VS 2行5列


In [17]:
a = np.arange(1,3).reshape(2,1)
print(a)
b = np.arange(11,21).reshape(2,5)
print(b)

print(f"a+b的值是{a+b}")

print(f"a*b的值是{a*b}")

[[1]
 [2]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
a+b的值是[[12 13 14 15 16]
 [18 19 20 21 22]]
a*b的值是[[11 12 13 14 15]
 [32 34 36 38 40]]


#### 不同维度


In [18]:
a = np.arange(1,13).reshape(3,4)
print(a)
b = np.arange(1,11).reshape(2,5)
print(b)

print(f"a+b的值是{a+b}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


ValueError: operands could not be broadcast together with shapes (3,4) (2,5) 

### 5、数组中的转置
转置是一种变换,对于numpy中的数组来说,就是在对角线方向交换数据,目的也是为了更方便的去处理数据

In [22]:
t = np.array([[ 0,  1,  2,  3,  4,  5],[ 6,  7,  8,  9, 10, 11],[12, 13, 14, 15, 16, 17]])
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [23]:
t.transpose()

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [24]:
t.swapaxes(1,0)

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [25]:
t.T

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

###  6、数组的拼接
数组水平或者竖直拼接很简单，但是拼接之前应该注意什么？  
竖直拼接的时候：每一列代表的意义相同！！！否则牛头不对马嘴

如果每一列的意义不同，这个时候应该交换某一组的数的列，让其和另外一类相同

In [26]:
t1 = np.arange(0,12).reshape(2,6)
print(t1)
print("\n")
t2 = np.arange(12,24).reshape(2,6)
print(t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [27]:
np.vstack((t1,t2)) # 竖直拼接

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [28]:
np.hstack((t1,t2)) # 水平拼接

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])

###  7、数组的行列交换


In [34]:
t = np.arange(12,24).reshape(3,4)
t

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
t[[1,2],:] = t[[2,1],:] # 行交换
t

array([[12, 13, 14, 15],
       [20, 21, 22, 23],
       [16, 17, 18, 19]])

In [36]:
t[:,[0,2]] = t[:,[2,0]] # 列交换
t

array([[14, 13, 12, 15],
       [22, 21, 20, 23],
       [18, 17, 16, 19]])

###  8、数组中的clip(裁剪)


In [37]:
t = np.arange(0,20).reshape(5,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
t.clip(9,10) # 小于9的修改为9，大于10的修改为10

array([[ 9,  9,  9,  9],
       [ 9,  9,  9,  9],
       [ 9,  9, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

clip 函数，clip 函数用于将数组中的元素限制在某个范围内，即小于某个最小值的元素将被设置为这个最小值，大于某个最大值的元素将被设置为这个最大值。

In [42]:
###  9、数组中数值的修改
t = np.arange(0,20).reshape(5,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
t[0,0] = 100
t

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19]])

In [45]:
t[:,0:2] = 0
t

array([[ 0,  0,  2,  3],
       [ 0,  0,  6,  7],
       [ 0,  0, 10, 11],
       [ 0,  0, 14, 15],
       [ 0,  0, 18, 19]])

In [47]:
t[t<20] = 0
t

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
t[t==0] = 1 # 等于0的都修改为1
t

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## numpy常用方法
###  1、小技巧

In [50]:
## 1）获取最大值最小值的位置
t1 = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19])
print(t1)

print(np.argmax(t1,axis=0)) #返回最大值索引
print(np.argmin(t1,axis=0)) #返回最小值索引

# 多维数组就返回每行的最大或最小值
t2 = np.arange(0,16).reshape(4,4)
print(t2)

print(np.argmax(t2,axis=0)) #返回最大值索引
print(np.argmin(t2,axis=0)) #返回最小值索引

[11 12 13 14 15 16 17 18 19]
8
0
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[3 3 3 3]
[0 0 0 0]


In [51]:
## 2）创建一个全0的数组: `np.zeros((3,4))`
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
## 3）创建一个全1的数组：`np.ones((3,4))`
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
## 4）创建一个对角线为1的正方形数组(方阵)：`np.eye(3)`
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 2、生成随机数

| 方法                                           | 说明                                                         |
| ---------------------------------------------- | ------------------------------------------------------------ |
| `np.random.rand(d0, d1,.. dn)`                 | 创建d0-dn维度的均匀分布的随机数数组，浮点数，范围从0-1       |
| `np.random.randn(d0,d1,. .dn)`                 | 创建d0-dn维度的标准正态分布随机数，浮点数，平均数0，标准差1  |
| `np.random.randint(low, high,(shape))` (常用） | 从给定上下限范围选取随机数整数，范围是low,high,形状是shape   |
| `np.random.uniform( low, high,(size))`         | 产生具有均匀分布的小数数组，low起始值，high结束值，size形状  |
| `np.random.normal(loc, scale,(size))`          | 从指定正态分布中随机抽取样本，分布中心是loc (概率分布的均值) ,标准差是scale,形状是size |
| `np.random.seed(s)`                            | 随机数种子，s是给定的种子值。因为计算机生成的是伪随机数，所以通过设定相同的随机数种子，可以每次生成相同的随机数 |

In [54]:
np.random.randint(10,20,(3,3))

array([[16, 11, 10],
       [12, 16, 11],
       [15, 18, 12]])

In [55]:
np.random.randint(10,20,(3,3))

array([[15, 14, 17],
       [14, 13, 10],
       [18, 19, 19]])