## 一、字符串函数
是用于对`dtype`为`numpy.string`或`numpy.unicode`的数组执行向量化字符串操作基于Python内置库中的标准字符串函数在`字符数组类(numpy.char)`中定义

###  1、add()
对两个数组的元素进行字符串连接


In [1]:
import numpy as np

print(np.char.add(['hello'],['python']))

print(np.char.add(['hello','python'],['yyds']))

['hellopython']
['helloyyds' 'pythonyyds']


###  2、multiply()
返回按元素多重连接后的字符串

In [2]:
print(np.char.multiply(['hello'], 3))

['hellohellohello']


###  3、center()
将字符串居中，并使用指定字符在左侧和右侧进行填充

In [3]:
print(np.char.center(['hello', 'python'], 15, fillchar='-'))

['-----hello-----' '-----python----']


###  4、capitalize()
将字符串第一个字母转换为大写


In [4]:
print(np.char.capitalize(['hello', 'python']))

['Hello' 'Python']


###  5、title()
将字符串的每个单词的第一个字母转换为大写

In [5]:
print(np.char.title(['hello python']))

['Hello Python']


 ### 6、lower()
 数组元素转换为小写

In [6]:
print(np.char.lower(['Hello Python']))

['hello python']


###  7、upper()
数组元素转换为大写

In [7]:
print(np.char.upper(['Hello Python']))

['HELLO PYTHON']


### 8、split()
指定分隔符对字符串进行分割，并返回数组列表

In [8]:
print(np.char.split(['Hello Python'], sep=' '))

[list(['Hello', 'Python'])]


 ### 9、splitlines()
 返回元素中的行列表，以换行符分割
    

In [9]:
print(np.char.splitlines(['Hello\nPython\nyyds']))

[list(['Hello', 'Python', 'yyds'])]


###  10、strip()
移除元素开头或者结尾处的特定字符

In [10]:
print(np.char.strip(['--Hello--', '--python--'], '-'))

['Hello' 'python']


### 11、join()
通过指定分隔符来连接数组中的元素

In [12]:
print(np.char.join("*", ['Hello', 'python']))
print(np.char.join(["*", "-"], ['Hello--', 'python']))

['H*e*l*l*o' 'p*y*t*h*o*n']
['H*e*l*l*o*-*-' 'p-y-t-h-o-n']


### 12、replace()
使用新字符串替换字符串中的所有子字符串

In [13]:
print(np.char.replace(['Hello', 'python'], "python", "java"))

['Hello' 'java']


###  13、encode()
编码，数组元素依次调用str.encode


In [14]:
print(np.char.encode(['Hello', 'python'], "utf-8"))

[b'Hello' b'python']


## 二、数学函数

###  1、sin()、cos()、tan()
标准三角函数


In [15]:
a = np.array([0, 30, 45, 60, 90, 180])
print('不同角度的正弦值: ')
print(np.sin(a * np.pi / 180))

print('\n数组中角度的余弦值: ')
print(np.cos(a * np.pi / 180))

print('\n数组中角度的正切值: ')
print(np.tan(a * np.pi / 180))

不同角度的正弦值: 
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]

数组中角度的余弦值: 
[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -1.00000000e+00]

数组中角度的正切值: 
[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.22464680e-16]


###  2、arcsin()、arccos()、arctan()
反三角函数


In [17]:
a = np.array([0, 30, 45, 60, 90, 180])
print('计算角度的反正弦，返回值以弧度为单位: ')
print(np.arcsin(np.sin(a * np.pi / 180)))

print('计算角度的反余弦，返回值以弧度为单位: ')
print(np.arccos(np.cos(a * np.pi / 180)))

print('计算角度的反正切，返回值以弧度为单位: ')
print(np.arctan(np.tan(a * np.pi / 180)))



计算角度的反正弦，返回值以弧度为单位: 
[0.00000000e+00 5.23598776e-01 7.85398163e-01 1.04719755e+00
 1.57079633e+00 1.22464680e-16]
计算角度的反余弦，返回值以弧度为单位: 
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
计算角度的反正切，返回值以弧度为单位: 
[ 0.00000000e+00  5.23598776e-01  7.85398163e-01  1.04719755e+00
  1.57079633e+00 -1.22464680e-16]


### 3、numpy.around(a, decimals=0)：

**参数说明**：

* a：数组
* decimals：舍入的小数位数。默认值为0。 如果为负，整数将四舍五入到小数点左侧的位置

In [18]:
a = np.array([1.0, 2.22, 3.456, 4.4444, 5.5555, 12345])
print(a)

print(np.around(a))

print(np.around(a, decimals=1))

print(np.around(a, decimals=-1))

[1.0000e+00 2.2200e+00 3.4560e+00 4.4444e+00 5.5555e+00 1.2345e+04]
[1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00 6.0000e+00 1.2345e+04]
[1.0000e+00 2.2000e+00 3.5000e+00 4.4000e+00 5.6000e+00 1.2345e+04]
[0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+01 1.234e+04]


###  4、floor()
向下取整，反回不大于输入参数的最大整数。即标量x 的下限是最大的整数i，使得i <=X。注意在Python中， 向下取整总是从0舍入

In [19]:
a = np.array([1.0, 2.2, 3.4, 4.4, 5.5, 12345])
print(a)

print(np.floor(a))

[1.0000e+00 2.2000e+00 3.4000e+00 4.4000e+00 5.5000e+00 1.2345e+04]
[1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00 5.0000e+00 1.2345e+04]


### 5、ceil()
向上取整，返回输入值的上限，即，标量x的上限是最小的整数i，使得i>= x

In [20]:
a = np.array([1.0, 2.2, 3.4, 4.4, 5.5, 12345])
print(a)

print(np.ceil(a))

[1.0000e+00 2.2000e+00 3.4000e+00 4.4000e+00 5.5000e+00 1.2345e+04]
[1.0000e+00 3.0000e+00 4.0000e+00 5.0000e+00 6.0000e+00 1.2345e+04]


## 三、算术函数


 ### 1、add()，subtract()，multiply()，divide()
加减乘除


In [21]:
import numpy as np

x = np.arange(9, dtype="f").reshape(3, 3)
print(f"x数组:\n{x}")

y = np.array([10, 10, 10])
print(f"y数组:\n{y}")

print(f"两个数组相加:\n{np.add(x, y)}")

print(f"两个数组相减:\n{np.subtract(x, y)}")

print(f"两个数组相乘:\n{np.multiply(x, y)}")

print(f"两个数组相除:\n{np.divide(x, y)}")

x数组:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
y数组:
[10 10 10]
两个数组相加:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
两个数组相减:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
两个数组相乘:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
两个数组相除:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


###  2、reciprocal()
返回参数逐个元素的倒数

In [22]:
import numpy as np

x = np.arange(10)
# 打印原数组和它的倒数（reciprocal）
# 注意：整数数组的倒数会以整数形式返回，1/0会溢出（显示为-2147483648）
print(f"原始数组:\n{x}\n\n倒数结果:\n{np.reciprocal(x)}")

# 改进版本：使用浮点数数组计算倒数
x_float = np.arange(10, dtype=float)  # 转换为浮点类型
# 此时1/0会显示inf（无穷大），其他结果更精确
print(f"\n浮点数组:\n{x_float}\n\n倒数结果（浮点计算）:\n{np.reciprocal(x_float)}")

原始数组:
[0 1 2 3 4 5 6 7 8 9]

倒数结果:
[9223372036854775807                   1                   0
                   0                   0                   0
                   0                   0                   0
                   0]

浮点数组:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

倒数结果（浮点计算）:
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/var/folders/5k/3c9dfk_50vj2bq1j4ry_r0wr0000gn/T/ipykernel_14298/2763038274.py:6: RuntimeWarning: divide by zero encountered in reciprocal
  print(f"原始数组:\n{x}\n\n倒数结果:\n{np.reciprocal(x)}")
/var/folders/5k/3c9dfk_50vj2bq1j4ry_r0wr0000gn/T/ipykernel_14298/2763038274.py:6: RuntimeWarning: invalid value encountered in reciprocal
  print(f"原始数组:\n{x}\n\n倒数结果:\n{np.reciprocal(x)}")
/var/folders/5k/3c9dfk_50vj2bq1j4ry_r0wr0000gn/T/ipykernel_14298/2763038274.py:11: RuntimeWarning: divide by zero encountered in reciprocal
  print(f"\n浮点数组:\n{x_float}\n\n倒数结果（浮点计算）:\n{np.reciprocal(x_float)}")


###  3、power()
将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂


In [23]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 10, 10])

print(f"幂运算结果:\n{np.power(a, b)}")

幂运算结果:
[    1  1024 59049]


###  4、mod()、remainder()
计算输入数组中相应元素的相除后的余数

In [24]:
import numpy as np

a = np.array([10, 10, 10])
b = np.array([1, 2, 3])

print(f"取模运算(mod):\n{np.mod(a, b)}")
print(f"取余运算(remainder):\n{np.remainder(a, b)}")

取模运算(mod):
[0 0 1]
取余运算(remainder):
[0 0 1]


##  四、统计函数


###  1、amax()、amin()
计算数组中的元素沿指定轴的最大值、最小值

In [25]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(f"原始数组:\n{a}")

print(f"\n每列最大值:\n{np.amax(a, 0)}")
print(f"每行最大值:\n{np.amax(a, 1)}")

print(f"\n每列最小值:\n{np.amin(a, 0)}")
print(f"每行最小值:\n{np.amin(a, 1)}")

原始数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

每列最大值:
[ 8  9 10 11]
每行最大值:
[ 3  7 11]

每列最小值:
[0 1 2 3]
每行最小值:
[0 4 8]


###  2、ptp()
计算数组中元素最大值与最小值的差(最大值-最小值)

In [26]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(f"原始数组:\n{a}")

print(f"\n每列的极差(最大值-最小值):\n{np.ptp(a, axis=0)}")
print(f"每行的极差(最大值-最小值):\n{np.ptp(a, axis=1)}")

原始数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

每列的极差(最大值-最小值):
[8 8 8 8]
每行的极差(最大值-最小值):
[3 3 3]


###  3、numpy.percentile(a, q,axis)
百分位数是统计中使用的度量、表示小于这个值的观察值的百分比  
**参数说明**：

* a：输入数组
* p：要计算的百分位数，在0~ 100之间（第p个百分位数是这样一个值， 它使得至少有p%的数据项小于或等于这个值，且至少有(100-p)%的数据项大于或等于这个值）
* axis：沿着它计算百分位数的轴

In [27]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(f"原始数组:\n{a}")

# 计算整个数组的中位数(50%分位数)
print(f"\n整个数组的中位数: {np.percentile(a, 50)}")

# 沿列方向计算中位数
print(f"每列的中位数: {np.percentile(a, 50, axis=0)}")

# 沿行方向计算中位数
print(f"每行的中位数: {np.percentile(a, 50, axis=1)}")

# 沿行方向计算中位数并保持维度
print(f"\n每行的中位数(保持维度):\n{np.percentile(a, 50, axis=1, keepdims=True)}")

原始数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

整个数组的中位数: 5.5
每列的中位数: [4. 5. 6. 7.]
每行的中位数: [1.5 5.5 9.5]

每行的中位数(保持维度):
[[1.5]
 [5.5]
 [9.5]]


### 此外还有sum，mean，median，std，这里只给一个例子


In [28]:
import numpy as np

# 创建3x4的二维数组
arr = np.arange(12).reshape(3, 4)
print(f"原始数组:\n{arr}\n")

# 统计计算
print("=== 全局统计 ===")
print(f"总和: {np.sum(arr)}")
print(f"均值: {np.mean(arr):.2f}")
print(f"中位数: {np.median(arr)}")
print(f"标准差: {np.std(arr):.2f}\n")

print("=== 列统计(axis=0) ===")
print(f"列总和: {np.sum(arr, axis=0)}")
print(f"列均值: {np.mean(arr, axis=0)}")
print(f"列中位数: {np.median(arr, axis=0)}")
print(f"列标准差: {np.std(arr, axis=0)}\n")

print("=== 行统计(axis=1) ===")
print(f"行总和: {np.sum(arr, axis=1)}")
print(f"行均值: {np.mean(arr, axis=1)}")
print(f"行中位数: {np.median(arr, axis=1)}")
print(f"行标准差: {np.std(arr, axis=1)}")

原始数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

=== 全局统计 ===
总和: 66
均值: 5.50
中位数: 5.5
标准差: 3.45

=== 列统计(axis=0) ===
列总和: [12 15 18 21]
列均值: [4. 5. 6. 7.]
列中位数: [4. 5. 6. 7.]
列标准差: [3.26598632 3.26598632 3.26598632 3.26598632]

=== 行统计(axis=1) ===
行总和: [ 6 22 38]
行均值: [1.5 5.5 9.5]
行中位数: [1.5 5.5 9.5]
行标准差: [1.11803399 1.11803399 1.11803399]


## 五、排序函数


###  1、sort(a, axis, kind, order)
返回输入数组的排序副本
**参数说明**：

* a：要排序的数组
* axis：沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序，axis=0按列排序，axis=1 按行排序  
  kind：排序算法，默认为’quicksort’
* order：如果数组包含字段，则是要排序的字段

In [29]:
import numpy as np

# 随机生成3x4数组并排序
x = np.random.randint(1, 11, 12).reshape(3, 4)
print(f"x数组:\n{x}")

print(f"\n默认按行排序:\n{np.sort(x)}")
print(f"\n按列排序:\n{np.sort(x, axis=0)}")

# 结构化数组排序
dt = np.dtype([('name', 'S10'), ('age', int)])
y = np.array([("xiaoming", 10), ("xiaoming", 20), ("xiaohong", 30), ("xiaobai", 40)], dtype=dt)
print(f"\ny数组:\n{y}")
print(f"\n按age字段排序:\n{np.sort(y, order='age')}")

x数组:
[[ 3  4 10  5]
 [ 6  1  6  3]
 [ 1  2  7  2]]

默认按行排序:
[[ 3  4  5 10]
 [ 1  3  6  6]
 [ 1  2  2  7]]

按列排序:
[[ 1  1  6  2]
 [ 3  2  7  3]
 [ 6  4 10  5]]

y数组:
[(b'xiaoming', 10) (b'xiaoming', 20) (b'xiaohong', 30) (b'xiaobai', 40)]

按age字段排序:
[(b'xiaoming', 10) (b'xiaoming', 20) (b'xiaohong', 30) (b'xiaobai', 40)]


###  2、argbort()
对输入数组沿给定轴执行间接排序，并使用指定排序类型返回数据的索引数组。这个索引数组用于构造排序后的数组


In [30]:
import numpy as np

# 创建示例数组
x = np.array([3, 1, 2])
print(f"原始数组:\n{x}")

# 使用argsort获取排序索引
sorted_indices = np.argsort(x)
print(f"\n排序后的索引:\n{sorted_indices}")

# 使用索引重构排序后的数组
print(f"\n通过索引重构的排序数组:\n{x[sorted_indices]}")

# 使用循环打印排序结果
print("\n通过循环打印排序结果:")
for idx in sorted_indices:
    print(x[idx])

原始数组:
[3 1 2]

排序后的索引:
[1 2 0]

通过索引重构的排序数组:
[1 2 3]

通过循环打印排序结果:
1
2
3


### 3、sort_ complex(a)
对复数按照先实部后虚部的顺序进行排序

In [31]:
import numpy as np

# 实数数组排序
x = np.array([100, 20, 30, 10, 50])
print(f"实数数组x:\n{x}")
print(f"\nx的复数形式排序结果:\n{np.sort_complex(x)}")

# 复数数组排序
y = np.array([1 + 2j, 2 - 1j, 3 - 2j, 3 - 3j, 3 + 5j])
print(f"\n复数数组y:\n{y}")
print(f"\ny的复数排序结果:\n{np.sort_complex(y)}")

实数数组x:
[100  20  30  10  50]

x的复数形式排序结果:
[ 10.+0.j  20.+0.j  30.+0.j  50.+0.j 100.+0.j]

复数数组y:
[1.+2.j 2.-1.j 3.-2.j 3.-3.j 3.+5.j]

y的复数排序结果:
[1.+2.j 2.-1.j 3.-3.j 3.-2.j 3.+5.j]
