## 一、拷贝

### 1、赋值

简单的赋值不会创建数组对象的副本。相反，它使用原始数组的相同id()来访问它。id()返回Python对象的通用标识符，类似于C中的指针。

一个数组的任何变化都反映在另-个数组上。例如，一个数组的形状改变也会改变另一个数组的形状


In [1]:
import numpy as np

# 创建原始数组
x = np.array([1, 2, 3, 4, 5, 6])
print(f"原始数组x:\n{x}")

# 显示内存地址
print(f"\nx的内存地址: {id(x)}")

# 创建数组引用
y = x
print(f"y的内存地址: {id(y)}")  # 与x相同，说明是同一对象

# 通过y修改形状
y.shape = (3, 2)
print(f"\n修改形状后的y:\n{y}")
print(f"修改后的x:\n{x}")  # x也随之改变，因为它们指向同一内存

原始数组x:
[1 2 3 4 5 6]

x的内存地址: 4461639792
y的内存地址: 4461639792

修改形状后的y:
[[1 2]
 [3 4]
 [5 6]]
修改后的x:
[[1 2]
 [3 4]
 [5 6]]


### 2、 视图

又可称为浅拷贝，是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。对视图进行修改，它会影响到原始数据，物理内存在同一位

发生情况：

* numpy的切片操作返回原数据的视图，修改数据会影响到原始数组

In [ ]:
import numpy as np

# 创建原始数组
x = np.arange(12)
print(f"原始数组x:\n{x}")

# 创建切片视图
y = x[3:]
print(f"\n切片y (x[3:]):\n{y}")

# 修改切片中的元素
y[1] = 100  # 这会同时修改原始数组x

print("\n修改y[1] = 100后:")
print(f"切片y:\n{y}")
print(f"原始数组x:\n{x}")  # 可以看到x[4]也被修改了

调用ndarray的view()函数产生一个视图创建一个新的数组对象，该方法创建的新数组的维数更改不会更改原始数据的维数

In [3]:
import numpy as np

# 创建原始3x2数组
x = np.arange(6).reshape((3, 2))
print(f"原始数组x:\n{x}")

# 创建视图
y = x.view()
print(f"\n视图数组y:\n{y}")

# 比较内存地址
print(f"\n内存地址比较:")
print(f"x的地址: {id(x)}")
print(f"y的地址: {id(y)}")  # 不同地址但共享数据

# 通过视图修改数据
y[1][0] = 100
print("\n修改y[1][0] = 100后:")
print(f"视图y:\n{y}")
print(f"原始x:\n{x}")  # x也被修改，说明共享数据内存

原始数组x:
[[0 1]
 [2 3]
 [4 5]]

视图数组y:
[[0 1]
 [2 3]
 [4 5]]

内存地址比较:
x的地址: 4467623472
y的地址: 4467623184

修改y[1][0] = 100后:
视图y:
[[  0   1]
 [100   3]
 [  4   5]]
原始x:
[[  0   1]
 [100   3]
 [  4   5]]


### 3、 副本

又可称为深拷贝，是一个数据的完整的拷贝，如果我们对副本进行修改，它不会影响到原始数据，物理内存不在同- -位置

发生情况：

* 调用ndarray的copy()函数产生一个副本
* 作用：创建一个副本
* 说明：对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置

In [4]:
import numpy as np

# 创建原始数组
x = np.array([[10, 10], [2, 3], [4, 5]])
print(f"原始数组x:\n{x}")

# 创建深层副本
y = x.copy()
print(f"\n副本数组y:\n{y}")

# 验证是否为独立副本
print(f"\n验证独立性:")
print(f"y is x? {y is x}")  # False表示是不同的对象
print(f"内存地址: x={id(x)}, y={id(y)}")

# 修改副本验证独立性
y[0][0] = 100
print(f"\n修改y[0][0]=100后:")
print(f"副本y:\n{y}")
print(f"原始x:\n{x}")  # x保持不变

原始数组x:
[[10 10]
 [ 2  3]
 [ 4  5]]

副本数组y:
[[10 10]
 [ 2  3]
 [ 4  5]]

验证独立性:
y is x? False
内存地址: x=4467624144, y=4466947248

修改y[0][0]=100后:
副本y:
[[100  10]
 [  2   3]
 [  4   5]]
原始x:
[[10 10]
 [ 2  3]
 [ 4  5]]


### 4、 注意点copy和view

* `a=b` ：完全不复制，a和b相互影响
* `a = b[:]`：视图的操作，一种切片，会创建新的对象a，但是a的数据完全由b保管，他们两个的数据变化是一致的，
* `a = b.copy()`：复制，a和b互不影响

## 二、numpy常用方法
### 1、 小技巧

1）获取最大值最小值的位置

In [5]:
import numpy as np

# 一维数组示例
t1 = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19])
print(f"一维数组t1:\n{t1}")
print(f"\n最大值索引: {np.argmax(t1)} (值={t1[np.argmax(t1)]})")
print(f"最小值索引: {np.argmin(t1)} (值={t1[np.argmin(t1)]})")

# 二维数组示例
t2 = np.arange(0,16).reshape(4,4)
print(f"\n二维数组t2:\n{t2}")

# 沿axis=0(列方向)查找极值索引
print("\n每列的最大值索引:", np.argmax(t2, axis=0))
print("每列的最小值索引:", np.argmin(t2, axis=0))

# 沿axis=1(行方向)查找极值索引
print("\n每行的最大值索引:", np.argmax(t2, axis=1))
print("每行的最小值索引:", np.argmax(t2, axis=1))

一维数组t1:
[11 12 13 14 15 16 17 18 19]

最大值索引: 8 (值=19)
最小值索引: 0 (值=11)

二维数组t2:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

每列的最大值索引: [3 3 3 3]
每列的最小值索引: [0 0 0 0]

每行的最大值索引: [3 3 3 3]
每行的最小值索引: [3 3 3 3]


2）全0全1对角线1的数组


In [6]:
import numpy as np

# 创建全零数组
zeros_arr = np.zeros((3,4))
print(f"3x4全零数组:\n{zeros_arr}\n")

# 创建全1数组
ones_arr = np.ones((3,4))
print(f"3x4全1数组:\n{ones_arr}\n")

# 创建3x3单位矩阵
eye3 = np.eye(3)
print(f"3x3单位矩阵:\n{eye3}\n")

# 创建10x10单位矩阵(只显示部分)
eye10 = np.eye(10)
print("10x10单位矩阵(部分显示):")
# 打印前3行和前5列，避免控制台输出过长
print(eye10[:3, :5])
print("... (其余部分省略) ...")

3x4全零数组:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

3x4全1数组:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3单位矩阵:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

10x10单位矩阵(部分显示):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
... (其余部分省略) ...


### 2、 生成随机数

| 方法                                           | 说明                                                         |
| ---------------------------------------------- | ------------------------------------------------------------ |
| `np.random.rand(d0, d1,.. dn)`                 | 创建d0-dn维度的均匀分布的随机数数组，浮点数，范围从0-1       |
| `np.random.randn(d0,d1,. .dn)`                 | 创建d0-dn维度的标准正态分布随机数，浮点数，平均数0，标准差1  |
| `np.random.randint(low, high,(shape))` (常用） | 从给定上下限范围选取随机数整数，范围是low,high,形状是shape   |
| `np.random.uniform( low, high,(size))`         | 产生具有均匀分布的小数数组，low起始值，high结束值，size形状  |
| `np.random.normal(loc, scale,(size))`          | 从指定正态分布中随机抽取样本，分布中心是loc (概率分布的均值) ,标准差是scale,形状是size |
| `np.random.seed(s)`                            | 随机数种子，s是给定的种子值。因为计算机生成的是伪随机数，所以通过设定相同的随机数种子，可以每次生成相同的随机数 |

In [7]:
import numpy as np

# 生成3x3随机整数矩阵（范围10-20）
random_matrix1 = np.random.randint(10, 20, (3, 3))
print(f"第一个3x3随机矩阵(10-20):\n{random_matrix1}\n")

# 再次生成不同的3x3随机整数矩阵
random_matrix2 = np.random.randint(10, 20, (3, 3))
print(f"第二个3x3随机矩阵(10-20):\n{random_matrix2}")

# 设置随机种子确保可重复性演示
np.random.seed(42)  # 设置随机种子
print("\n设置随机种子后(seed=42):")
consistent_matrix = np.random.randint(10, 20, (3, 3))
print(f"可重复的随机矩阵:\n{consistent_matrix}")

# 生成不同范围的随机矩阵示例
print("\n其他范围示例:")
print("5x5矩阵(0-100):\n", np.random.randint(0, 100, (5, 5)))

第一个3x3随机矩阵(10-20):
[[14 11 12]
 [16 13 16]
 [15 15 13]]

第二个3x3随机矩阵(10-20):
[[18 10 14]
 [10 11 12]
 [10 11 18]]

设置随机种子后(seed=42):
可重复的随机矩阵:
[[16 13 17]
 [14 16 19]
 [12 16 17]]

其他范围示例:
5x5矩阵(0-100):
 [[99 23  2 21 52]
 [ 1 87 29 37  1]
 [63 59 20 32 75]
 [57 21 88 48 90]
 [58 41 91 59 79]]


## 三、numpy中的nan和inf

**nan(NAN,Nan)：not a number表示不是一个数字**

**什么时候numpy中会出现nan：**

* 当我们读取本地的文件为float的时候，如果有缺失，就会出现nan
* 当做了一个不合适的计算的时候(比如无穷大(inf)减去无穷大)

**inf(-inf,inf):infinity,inf表示正无穷，-inf表示负无穷**

**什么时候回出现inf包括（-inf，+inf）**：

* 比如一个数字除以0，（python中直接会报错，numpy中是一个inf或者-inf）

In [8]:
import numpy as np

# 检查特殊值的类型
print(f"np.nan的类型: {type(np.nan)}")  # <class 'float'>
print(f"np.inf的类型: {type(np.inf)}")  # <class 'float'>

# 相关特殊值演示
print("\n特殊值运算示例:")
print(f"无穷大运算: {np.inf + 1}")      # 仍为inf
print(f"无穷大比较: {np.inf > 10**100}") # True
print(f"非数运算: {np.nan + 5}")        # 仍为nan
print(f"非数比较: {np.nan == np.nan}")   # False

# 检测特殊值的实用方法
arr = np.array([1, 2, np.nan, np.inf, 5])
print("\n特殊值检测:")
print(f"是否为无穷: {np.isinf(arr)}")  # [False False False  True False]
print(f"是否为非数: {np.isnan(arr)}")  # [False False  True False False]

np.nan的类型: <class 'float'>
np.inf的类型: <class 'float'>

特殊值运算示例:
无穷大运算: inf
无穷大比较: True
非数运算: nan
非数比较: False

特殊值检测:
是否为无穷: [False False False  True False]
是否为非数: [False False  True False False]
