# Numpy 入门基础教程
NumPy是一个开源 Python 库，几乎用于科学和工程的每个领域。  
它是在 Python 中处理数值数据的通用标准，也是科学 Python 和 PyData 生态系统的核心。  
NumPy API 广泛用于 Pandas、SciPy、Matplotlib、scikit-learn、scikit-image和许多数据科学Python包中。  

NumPy 库包含多维数组和矩阵数据结构。  
它提供了 ndarray，一个同构 n 维数组对象，以及对其进行有效操作的方法。


## 安装Numpy
在安装了python的前提下,通过pip进行安装。  

`pip install numpy`

In [115]:
# jupyter notebook中安装numpy方法
! pip install numpy

## 如何导入numpy
如下所示

In [116]:
import numpy as np

使用 NumPy 缩短导入的名称，以np提高代码的可读性。  
这是一种广泛采用的约定，可以使代码对于每个使用它的人都更具可读性。  
建议始终使用 import numpy as np。  

## Python 列表和 NumPy 数组有什么区别？
NumPy 为您提供了大量快速有效的方法来创建数组并操作其中的数字数据。  
虽然 Python 列表可以在单个列表中包含不同的数据类型，但 NumPy 数组中的所有元素都应该是同类的。  
如果数组不是同质的，则对数组执行的数学运算将非常低效。  

NumPy 数组比 Python 列表更快、更紧凑。数组占用内存少，使用方便。  
NumPy 使用更少的内存来存储数据，并且提供了指定数据类型的机制。这使得代码可以进一步优化。


### 什么是数组？
数组是 NumPy 库的核心数据结构。  
数组是一个值网格，它包含有关原始数据、如何定位元素以及如何解释元素的信息。 

数组可以通过非负整数元组、布尔值、另一个数组或整数进行索引。  


我们初始化 NumPy 数组的一种方法是使用 Python 列表，对二维或更高维的数据使用嵌套列表。
如下所示


In [117]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [118]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
## 查看数组的维数（ndim）
print(f"a的维数是 {a.ndim}，b的维数是 {b.ndim}")
print(f"a的形状是 {a.shape}，b的形状是 {b.shape}")

a的维数是 1，b的维数是 2
a的形状是 (6,)，b的形状是 (2, 3)


我们可以使用方括号访问数组中的元素。  
当访问元素时，请记住 NumPy 中的索引从 0 开始。这意味着如果想访问数组中的第一个元素，将访问元素“0”。

In [120]:
## 索引查找
print(b[0])

[1 2 3]


## 有关数组的更多信息
可能偶尔会听到称为“ndarray”的数组，它是“N 维数组”的简写。  
N 维数组就是具有任意维数的数组。  

可能还会听到1-D或一维数组、2-D或二维数组等等。   
NumPyndarray类用于表示矩阵和向量。    
向量是单维数组（行向量和列向量没有区别），而矩阵是指二维数组。对于3 维或更高维的数组，术语 “张量”也很常用。



### 数组有哪些属性？
数组通常是相同类型和大小的项目的固定大小容器。  
数组中的维数和项数由其形状定义。    
数组的形状是指定每个维度大小的非负整数元组。    
在 NumPy 中，维度称为轴。这意味着如果您有一个如下所示的二维数组：  
```python
[[0., 0., 0.],
 [1., 1., 1.]]
```
你的数组有 2 个轴。第一个轴的长度为 2，第二个轴的长度为 3。

## 如何创建一个基本数组
要创建 NumPy 数组，可以使用函数`np.array()`。
例如：
```python
import numpy as np
a = np.array([1, 2, 3])
```

除了从元素序列创建数组之外，还可以轻松创建用0'还有1 填充的数组：

In [121]:
np.zeros(2)

array([0., 0.])

In [122]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [123]:
np.ones(4)

array([1., 1., 1., 1.])

In [124]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

在 NumPy 中  
`np.empty(shape)` 会创建一个给定形状的新数组，但不会初始化数组的值  
这意味着它的内容取决于当前内存的状态（可能是任意值，甚至是垃圾值）

In [125]:
## 由于内存状态不同，每次运行结果可能不同
np.empty((3, 3))

array([[1.27189941e-30, 2.54379882e-30, 6.35949704e-31],
       [2.54379882e-30, 5.53276243e-30, 1.71706420e-30],
       [6.35949704e-31, 1.71706420e-30, 9.85722042e-31]])

In [126]:
## 可以创建一个包含一系列元素的数组：

np.arange(4)

array([0, 1, 2, 3])

In [127]:
## 甚至是包含一系列均匀间隔的数组。为此，您将指定第一个数字、最后一个数字和步长。

np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [128]:
## 还可以使用np.linspace()以指定间隔线性间隔的值创建数组

np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [129]:
## 虽然默认数据类型是浮点 ( np.float64)，但您可以使用关键字显式指定所需的数据类型dtype
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

## 添加、删除和排序元素
本节涵盖 np.sort()，np.concatenate()  

对元素进行排序很简单`np.sort()`。可以在调用函数时指定轴、种类和顺序。


In [130]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
## 排序
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

除了返回数组的排序副本的排序之外，还可以使用：  
argsort，这是沿指定轴的间接排序，  
lexsort，这是对多个键的间接稳定排序，  
searchsorted，它将在排序数组中查找元素，  
partition，这是部分排序。  


将数组连接起来使用`np.concatenate()`

In [131]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## 你如何知道数组的形状和大小？
本节涵盖 ndarray.ndim, ndarray.size,ndarray.shape  

`ndarray.ndim`会告诉您数组的轴数或维数。

`ndarray.size`会告诉你数组元素的总数。这是数组形状元素的乘积

`ndarray.shape`将显示一个整数元组，指示沿数组每个维度存储的元素数量。例如，如果您有一个 2 行 3 列的二维数组，则数组的形状为。(2, 3)


In [133]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [134]:
# 维数
array_example.ndim

3

In [135]:
# 元素总数
array_example.size

24

In [136]:
# 数组形状
array_example.shape

(3, 2, 4)

## 你能重塑一个数组吗？
本节涵盖 arr.reshape()    
使用`arr.reshape()`将为数组提供新的形状而不更改数据。  
当你使用 reshape 方法时，要生成的数组需要与原始数组具有相同数量的元素。如果你从包含 12 个元素的数组开始，则需要确保新数组也总共包含 12 个元素。

In [137]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [138]:
# 重塑
b = a.reshape((2,3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [139]:
# 使用np.reshape，可以指定一些可选参数：
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

`a`是要重塑的数组。  
`shape`是你想要的新形状。可以指定一个整数或整数元组。如果指定一个整数，结果将是该长度的数组。  
`order='C'`（行优先，默认）,`order='F'`（列优先）

## 如何将一维数组转换为二维数组（如何向数组添加新轴）
本节涵盖 np.newaxis，np.expand_dims  
使用`np.newaxis`一次后，数组的维度就会增加一维。这意味着1D数组将变成2D数组， 2D数组将变成3D数组，依此类推。

In [140]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [141]:
a2 = a[np.newaxis, :]

print(a2.shape)
a2

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [142]:
a3 = a2[np.newaxis, :, :]  # 在第0轴插入
print(a3.shape) 
a3

(1, 1, 6)


array([[[1, 2, 3, 4, 5, 6]]])

In [143]:
a3 = a2[:, np.newaxis, :] # 在第1轴插入
print(a3.shape)  
a3

(1, 1, 6)


array([[[1, 2, 3, 4, 5, 6]]])

In [144]:
a3 = a2[:, :, np.newaxis] # 在第2轴插入
print(a3.shape)  
a3

(1, 6, 1)


array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

还可以通过在指定位置插入新轴来扩展数组np.expand_dims

In [145]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

(6,)


In [146]:
## 使用np.expand_dims以下命令在索引位置 1 添加轴：
b = np.expand_dims(a, axis=1)
print(b.shape)
b

(6, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [147]:
## 使用以下命令在索引位置 0 添加轴：
c = np.expand_dims(a, axis=0)
print(c.shape)
c

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

## 索引和切片


In [148]:
data = np.array([1, 2, 3])

print(data[0])

print(data[1])

print(data[0:2])

print(data[1:])

print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


如果想从数组中选择满足特定条件的值，使用 NumPy 就很简单。  
例如：

In [149]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [150]:
# 轻松打印数组中所有小于 5 的值
print(a[a < 5])

[1 2 3 4]


In [151]:
# 选择能被 2 整除的元素
print(a[a%2==0])

[ 2  4  6  8 10 12]


In [152]:
# 还可以使用逻辑运算符&和|为了返回指定数组中的值是否满足特定条件的布尔值。这对于包含名称或其他分类值的数组非常有用。
print((a > 5) | (a == 5))

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [153]:
# 还可以用于np.nonzero()从数组中选择元素或索引。
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

# 用np.nonzero()打印小于 5 的元素的索引
b = np.nonzero(a < 5)
print(b)
# 在此示例中，返回了一个数组元组：每个维度一个。第一个数组表示找到这些值的行索引，第二个数组表示找到这些值的列索引。

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [154]:
# 如果要生成元素所在的坐标列表，可以压缩数组，迭代坐标列表，然后打印它们。例如：
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


## 如何从现有数据创建数组
你可以轻松地从现有数组的一部分创建新数组。

假设你有这个数组：`a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])`


In [155]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 随时通过指定要对数组进行切片的位置来从数组的一部分创建新数组。
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [156]:
## 还可以垂直和水平堆叠两个现有阵列。假设您有两个数组，a1并且a2：
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [157]:
## 使用以下命令垂直堆叠它们vstack
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [158]:
## 使用以下命令水平堆叠它们hstack
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

使用将一个数组拆分为多个较小的数组hsplit。  
可以指定要返回的形状相同的数组的数量或 应在其后进行除法的列。

In [159]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [160]:
##  把这个数组分成三个形状相同的数组
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [161]:
# 如果想在第三列和第四列之后拆分数组，您可以运行：
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

视图是一个重要的 NumPy 概念！ NumPy 函数以及索引和切片等操作将尽可能返回视图。这可以节省内存并且速度更快（无需复制数据）。然而，重要的是要注意这一点 - 修改视图中的数据也会修改原始数组！



In [162]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [163]:
b1 = a[0, :] # 通过切片创建 b1（实际是视图，不是副本）
b1

array([1, 2, 3, 4])

In [164]:
b1[0] = 100
print(b1)
print(a) #a[0,0]的位置元素也被修改成了100

[100   2   3   4]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [165]:
# 使用该copy方法将制作数组及其数据的完整副本（ 深层副本）。要在你的阵列上使用它，你可以运行：
b2 = a.copy()
print(b2) # copy后的b2

b2[0,0] = 200
print(b2)# 修改b2

print(a) # 现在的a（copy时，不变）

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[200   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## 基本数组操作
本节涵盖加法、减法、乘法、除法等

In [166]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data+ones # 加

array([2, 3])

In [167]:
data - ones # 减

array([0, 1])

In [168]:
data * data # 乘

array([1, 4])

In [169]:
data / data # 除

array([1., 1.])

如果你想求数组中元素的总和，你可以使用sum().这适用于一维数组、二维数组和更高维度的数组。

In [170]:
a = np.array([1, 2, 3, 4])
a.sum()

np.int64(10)

In [171]:
b = np.array([[1, 1], [2, 2]])

## 使用以下方法对行轴求和  
b.sum(axis=0)

array([3, 3])

In [172]:
## ## 使用以下方法对列轴求和 
b.sum(axis=1)

array([2, 4])

## 广播
有时你可能想要在数组和单个数字之间或在两个不同大小的数组之间执行运算  
例如，你的数组（我们将其称为“数据”）可能包含有关英里距离的信息，但你希望将信息转换为公里

NumPy 知道每个单元格都应该进行乘法。这个概念称为广播。  
广播是一种允许 NumPy 对不同形状的数组执行操作的机制。  
数组的维度必须兼容，例如，当两个数组的维度相等或其中一个数组的维度为 1 时。  

如果维度不兼容，您将得到一个ValueError.


In [173]:
data = np.array([1.0, 2.0])
data*1.6

array([1.6, 3.2])

## 更有用的数组操作
本节涵盖最大值、最小值、总和、平均值、乘积、标准差等  

NumPy 还执行聚合函数。除了min、max、 和 之外sum,您还可以轻松运行mean来获取平均值、prod获取元素相乘的结果、std获取标准差等等。  

想要沿着行或列聚合是很常见的。默认情况下，每个 NumPy 聚合函数都会返回整个数组的聚合。

In [174]:
data = np.array([[1,3,5,7,9],[2,4,6,8,10]])
data

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [175]:
## 最大值
print(f"data中的最大值{data.max()}")

## 最小值
print(f"data中的最小值{data.min()}")

## 总和
print(f"data中的总和{data.sum()}")

## 平均值
print(f"data中的平均值{data.mean()}")

## 相乘
print(f"data中的行轴相乘{data.prod(0)}")

## 相乘
print(f"data中的列轴相乘{data.prod(1)}")

## 标准差
print(f"data中的行标准差{data.std(0)}")

## 标准差
print(f"data中的列标准差{data.std(1)}")



data中的最大值10
data中的最小值1
data中的总和55
data中的平均值5.5
data中的行轴相乘[ 2 12 30 56 90]
data中的列轴相乘[ 945 3840]
data中的行标准差[0.5 0.5 0.5 0.5 0.5]
data中的列标准差[2.82842712 2.82842712]


## 创建矩阵
可以传递 Python 列表列表来创建二维数组（或“矩阵”）以在 NumPy 中表示它们。

In [176]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [177]:
## 索引和切片操作
print(data[0,1])

print(data[1:3])

print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


对不同大小的矩阵执行这些算术运算，但前提是一个矩阵只有一列或一行。在这种情况下，NumPy 将使用其广播规则进行操作。

In [178]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

请注意，当 NumPy 打印 N 维数组时，最后一个轴的循环速度最快，而第一个轴的循环速度最慢。例如：

In [179]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

在很多情况下，我们希望 NumPy 初始化数组的值。  
NumPy 提供了ones()和等函数zeros()，以及 random.Generator用于生成随机数的类  
您需要做的就是传入您希望它生成的元素数量：  

In [180]:
print(np.ones(3))

print(np.zeros(3))

print(np.random.rand(3))

[1. 1. 1.]
[0. 0. 0.]
[0.90904497 0.68734877 0.21410216]


In [181]:
# 如果给它们一个描述矩阵维度的元组，你还可以使用ones()、zeros()和random()创建一个二维数组：
print(np.ones((3, 2)))

print(np.zeros((3, 2)))

print(np.random.rand(3,2))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.42064343 0.21836929]
 [0.50403831 0.01220628]
 [0.56969475 0.2412046 ]]


## 生成随机数
随机数生成的使用是许多数值和机器学习算法的配置和评估的重要组成部分。 
 
无论你需要随机初始化人工神经网络中的权重、将数据拆分为随机集，还是随机洗牌数据集，能够生成随机数（实际上是可重复的伪随机数）都是至关重要的。

In [182]:
# 生成 2x4 的随机整数数组，范围 [0, 4)
arr = np.random.randint(low=0, high=4, size=(2, 4))
print(arr)

[[2 3 2 3]
 [1 2 1 1]]


### 注意事项

#### 范围包含性：
 high=4 表示生成的随机数最大为 3（不包括 4）。
 如果需要包含 4，改为 high=5。
#### 固定随机种子：
```python
np.random.seed(42)  # 设置种子后，每次运行结果相同
arr = np.random.randint(0, 4, (2, 4))
```
#### 生成浮点数：
如果需要浮点数，改用 np.random.uniform()：
```python
arr_float = np.random.uniform(low=0, high=4, size=(2, 4))
```

## 如何获得独特的物品和数量
本节涵盖 np.unique()  
可以使用 轻松找到数组中的唯一元素np.unique


In [183]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)

print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


要获取 NumPy 数组中唯一值的索引（数组中唯一值的第一个索引位置的数组），只需传入参数return_index 以及np.unique()数组即可。

In [184]:
unique_values, indices_list = np.unique(a, return_index=True)
indices_list  # 唯一值索引

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

可以将return_counts参数np.unique()与数组一起传递，以获取 NumPy 数组中唯一值的频率计数。

In [185]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
occurrence_count

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1])

这也适用于二维数组！如果你从这个数组开始：

In [186]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [187]:
unique_values = np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

如果未传递 axis 参数，你的 2D 数组将被展平。

如果你想获取唯一的行或列，请确保传递参数axis 。要查找唯一的行，请指定axis=0，对于列，请指定 axis=1。

In [188]:
unique_rows = np.unique(a_2d, axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [189]:
unique_cols = np.unique(a_2d, axis=1)
unique_cols

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

要获取唯一行、索引位置和出现次数，你可以使用：

In [190]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


## 转置和重塑矩阵
本节涵盖 arr.reshape(), arr.transpose(),arr.T

需要转置矩阵是很常见的。 NumPy 数组具有T允许你转置矩阵的属性 。

可能还需要切换矩阵的维度。例如，当你的模型需要与数据集不同的特定输入形状时，就会发生这种情况。这就是该reshape方法可以发挥作用的地方。你只需传入矩阵所需的新维度即可。



In [191]:
data = np.arange(6)
print(data)

data1 = data.reshape(2,3)
print(data1)

data2 = data.reshape(3,2)
print(data2)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


还可以.transpose()根据指定的值反转或更改数组的轴。


In [192]:
arr = np.arange(6).reshape((2, 3))
print(arr)

print(arr.transpose()) 

# 还可以使用arr.T：
print(arr.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


## 如何反转数组
本节涵盖 np.flip()  
NumPy 的np.flip()函数允许你沿轴翻转或反转数组的内容。使用 时np.flip()，指定要反转的数组和轴。  
如果你不指定轴，NumPy 将沿输入数组的所有轴反转内容。

### 反转一维数组


In [193]:
arr = np.array([1,2,3,4,5,6,7,8])
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

### 反转二维数组


In [194]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [195]:
## 可以轻松地仅反转行：
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [196]:
## 或者仅反转列：
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [197]:
## 还可以仅反转一列或一行的内容。例如，你可以反转索引位置 1 处的行内容（第二行）：
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [198]:
## 还可以反转索引位置 1 处的列（第二列）：
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## 重塑和展平多维数组
本节涵盖 .flatten()，ravel()

有两种流行的方法来展平数组：.flatten()和.ravel()。

两者之间的主要区别在于，使用创建的新数组 ravel()实际上是对父数组（即“视图”）的引用。  
这意味着对新数组的任何更改也会影响父数组。由于ravel不创建副本，因此内存效率很高。  

In [199]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [200]:
a1 = x.flatten()
a1[0] = 99
print(x) 
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [201]:
## 但是当你使用 时ravel，对新数组所做的更改将影响父数组。
a2 = x.ravel()
a2[0] = 98
print(x)
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


## 如何访问文档字符串以获取更多信息
本节涵盖 help(), ?,??

Python 和 NumPy 都是以用户为中心而构建的。最好的例子之一就是对文档的内置访问。每个对象都包含对字符串的引用，该字符串称为docstring。在大多数情况下，此文档字符串包含对象及其使用方法的快速而简洁的摘要。 Python 有一个内置help() 函数可以帮助你访问此信息。这意味着几乎任何时候你需要更多信息时，你都可以使用help()它来快速查找所需的信息。

In [202]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



由于访问附加信息非常有用，因此 IPython 使用该? 字符作为访问此文档以及其他相关信息的简写。 IPython 是一种用于多种语言交互式计算的命令 shell

In [203]:
## 自己运行一下这个看看就好了
max?

In [204]:
# 你甚至可以将此表示法用于对象方法和对象本身。
# 假设你创建了这个数组：
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [205]:
a?

这也适用于你创建的函数和其他对象。只需记住使用字符串文字（或在文档周围）在你的函数中包含文档字符串。""" """''' '''

例如，如果你创建此函数：


In [206]:
def double(a):
  '''Return a * 2'''
  return a * 2

In [207]:
## 可以获取有关该功能的信息：
double?

可以通过阅读你感兴趣的对象的源代码来获得另一个级别的信息。使用双问号 ( ??) 允许你访问源代码。

In [208]:
## 运行后自己看
double??

## 如何保存和加载 NumPy 对象
本节涵盖 np.save, np.savez, np.savetxt, np.load,np.loadtxt  

在某些情况下，你可能需要将 NumPy 数组保存到磁盘并在之后重新加载，而不必重新运行生成这些数组的代码。NumPy 提供了多种灵活的方式来保存和加载数组数据：

1. 对于文本格式的存储，可以使用 `savetxt` 和 `loadtxt` 函数来处理普通的文本文件
2. 对于高效的二进制存储，可以使用 `save` 和 `load` 函数来处理扩展名为 .npy 的 NumPy 二进制文件
3. 如果需要保存多个数组到一个文件中，可以使用 `savez` 函数来处理扩展名为 .npz 的 NumPy 归档文件

这些方法为不同的使用场景提供了便捷的数据持久化解决方案，你可以根据具体需求选择最适合的格式。

.npy和.npz文件以允许正确检索数组的方式存储重建 ndarray 所需的数据、形状、dtype 和其他信息，即使文件位于具有不同体系结构的另一台计算机上也是如此。

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
## 你可以使用以下命令将其另存为“filename.npy”：
np.save('filename', a)

## 你可以使用它np.load()来重建你的数组。
b = np.load('filename.npy')

## 如果你想检查你的数组，你可以运行：
print(b)


## 导入和导出 CSV
读取包含现有信息的 CSV 非常简单。最好、最简单的方法是使用 Pandas。


In [209]:
import pandas as pd
x = pd.read_csv('../数据集/data.csv', header=0).values
print(x)

[[  0.          17.4507123 ]
 [  1.01010101  10.45128801]
 [  2.02020202  24.76583312]
 [  3.03030303  40.42120542]
 [  4.04040404  16.58870948]
 [  5.05050505  19.11420827]
 [  6.06060606  48.83970738]
 [  7.07070707  39.18828861]
 [  8.08080808  23.15990441]
 [  9.09090909  40.86567338]
 [ 10.1010101   28.30125986]
 [ 11.11111111  30.79183147]
 [ 12.12121212  43.93246438]
 [ 13.13131313  14.12907916]
 [ 14.14141414  19.47976787]
 [ 15.15151515  39.44447494]
 [ 16.16161616  35.2115736 ]
 [ 17.17171717  57.64300292]
 [ 18.18181818  41.83418432]
 [ 19.19191919  36.79524246]
 [ 20.2020202   82.48978204]
 [ 21.21212121  59.64365852]
 [ 22.22222222  66.56847863]
 [ 23.23232323  46.70958529]
 [ 24.24242424  62.44031974]
 [ 25.25252525  74.79515198]
 [ 26.26262626  58.391662  ]
 [ 27.27272727  83.81728846]
 [ 28.28282828  71.69749036]
 [ 29.29292929  78.85691699]
 [ 30.3030303   76.73197657]
 [ 31.31313131 116.06700105]
 [ 32.32323232  90.60562244]
 [ 33.33333333  77.4676694 ]
 [ 34.34343434

使用 Pandas 导出数组也很简单。如果您是 NumPy 新手，您可能需要根据数组中的值创建 Pandas 数据框，然后使用 Pandas 将数据框写入 CSV 文件。

In [210]:
## 如果你创建了这个数组“a”
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])

## 可以创建一个 Pandas 数据框
df = pd.DataFrame(a)
print(df)

          0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928


In [ ]:
## 可以使用以下方法轻松保存数据框
df.to_csv('pd.csv')

## 使用以下命令读取你的 CSV：
data = pd.read_csv('pd.csv')